version: "3.8"
services:
  db-service:
    image: mysql:8.0.27
    container_name: db-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: subject_approval_service
    ports:
      - "3306:3306"
    networks:
      - staging-deploy

  phpmyadmin-service:
    image: phpmyadmin/phpmyadmin:5.1.3
    container_name: phpmyadmin-container
    restart: always
    secrets:
      - db_root_password
    environment:
      PMA_HOST: db-service
      PMA_USER: root
      PMA_PASSWORD: password
      PMA_ARBITRARY: 1
      PMA_PORT: 3306

    links:
      - 'db-service:db'
    ports:
      - "8885:80"
    networks:
      - staging-deploy

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - staging-deploy

  backend_service:
    image: subject-approval-image
    container_name: subject-approval-service-container
    restart: always
    env_file:
      - .env.example
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "4000:80"
    networks:
        -  staging-deploy

networks:
  staging-deploy:






