# # ### Deployment + Service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-admin-deployment
  labels:
    app: pg-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-admin
  template:
    metadata:
      labels:
        app: pg-admin
    spec:
      containers:
        - name: pg-admin
          # image: dpage/pgadmin4:6.17
          image: dpage/pgadmin4
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-admin-secrets
                  key: PG_USER_PASSWORD
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pg-admin-secrets
                  key: PG_USER_EMAIL
            - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
              value: 'False'
---
apiVersion: v1
kind: Service
metadata:
  name: pg-admin-service
spec:
  type: NodePort

  selector:
    app: pg-admin
  ports:
    - protocol: TCP
      port: 80 # cualquier puerto
      targetPort: 80
      nodePort: 30200



# # ### Deployment + Service

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: pg-admin-deployment
#   labels:
#     app: pg-admin

# spec: # definicion del POD
#   replicas: 1
#   selector:
#     matchLabels:
#       app: pg-admin
#   template:
#     metadata:
#       labels:
#         app: pg-admin
#     spec:
#       containers:
#         - name: pg-admin
#           image: dpage/pgadmin4:6.17
#           ports:
#             - containerPort: 80
#           env:
#             - name: PGADMIN_DEFAULT_PASSWORD      # tal cual lo pide la Img
#               valueFrom:
#                 secretKeyRef:
#                   name: pg-admin-secrets # name del secret en el yml, no file name, del metadata
#                   key: PG_USER_PASSWORD
#             - name: PGADMIN_DEFAULT_EMAIL      # tal cual lo pide la Img
#               valueFrom:
#                 secretKeyRef:
#                   name: pg-admin-secrets # name del secret en el yml, no file name, del metadata
#                   key: PG_USER_EMAIL
#             - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
#               vale: false

# # le dice a yml q es otro file
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: pg-admin-service
# spec:
#   type: NodePort   # permite comunication externa
#   selector:
#     app: pg-admin
#   ports:
#     - protocol: TCP
#       port: 80   # puerto q permite connection con el mundo exterior
#       targetPort: 80    # port del containerPort  <-  dentro del cluster
#       nodePort: 30200         # dentro del rango (30_000-32_000)

