version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=mysecretpassword

    # Connection:
    # host: postgres
    # user: postgres
    # pass: mysecretpassword

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '80:80'
    depends_on:
      - postgres
