version: '3.9'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_moodle:/bitnami/mariadb'
    ports:
      - '3306:3306'


  moodle:
    image: docker.io/bitnami/moodle:4.1
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data_m1:/bitnami/moodle'
      - 'moodledata_data_m1:/bitnami/moodledata'
    depends_on:
      - mariadb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    ports:
      - '8081:80'
    depends_on:
      - mariadb

volumes:
  mariadb_moodle:
    external: true
  moodle_data_m1:
    external: true
  moodledata_data_m1:
    external: true
