version: '3.7'

volumes:
  esdata:
    driver: local

services:
  #SIGN-UPS (APP)
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    container_name: app-sign-ups-test
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      #        -  /app/vendor    #Deshabilitar para desarrollo
      #- ./etc/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      #- ./etc/docker/php/fpm-pool.conf:/etc/php81/php-fpm.d/www.conf
      #- ./etc/docker/supervisor/supervisord.conf:/etc/supervisord.conf
    networks:
      - sign-ups-net

  # RABBITMQ (APP)
  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq-sign-ups-test
    tty: true
    environment:
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    extra_hosts:
      - "sign-ups-app:10.1.146.89"  
    networks:
      - sign-ups-net

  # ELASTICSEARCH (APP)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch-sign-ups-test
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - sign-ups-net

networks:
  sign-ups-net:
    external:
      name: ctdesarrollo-with-vpn

# networks:
#   sign-ups-net:
#     external: true
