version: '3.7'
        
services:    
    app:
        build: .
        ports:
            - 8080:8080
        volumes:
            - .:/app
            - /app/vendor
            - ./etc/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./etc/docker/php/fpm-pool.conf:/etc/php81/php-fpm.d/www.conf