version: "3.1"

services:
    db:
        image: mysql:8.0.32 
        restart: always
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: dbname
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default

    www:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html
        depends_on:
            - db

    phpmyadmin:
        image: phpmyadmin:5.2.1-apache
        links: 
            - db:db
        depends_on:
            - db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test


volumes:
    persistent:
