apiVersion: batch/v1
kind: CronJob
metadata:
  name: sign-ups-cronjob-consume-queue-test
  namespace: academic-administration-test
spec:
  schedule: "*/2 * * * *" #At every 2nd minute. https://crontab.guru/#*/2_*_*_*_*
  suspend: false
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: sign-ups-cronjob-test
            image: PHP_IMAGE_NAME
            envFrom:
            - secretRef:
                name: sign-ups-app-secret-test
            - configMapRef:
                name: sign-ups-app-config-test
            args:
            - /bin/sh
            - -c
            - php /app/artisan queue:consume --message-limit=200 --time-limit=20 --memory-limit=50
          restartPolicy: OnFailure
