apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sign-ups-app
  name: sign-ups-app
  namespace: academic-administration-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sign-ups-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        namespace: academic-administration-test
        app: sign-ups-app
    spec:
      restartPolicy: Always
      containers:
        - name: sign-ups-app-kernel
          image: PHP_IMAGE_NAME
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
          envFrom:
            - configMapRef:
                name: sign-ups-app-config-test
            - secretRef:
                name: sign-ups-app-secret-test
          resources:
            requests:
              cpu: 100m
              memory: 200Mi      
