apiVersion: v1
kind: Secret
metadata:
  name: subject-approval-secrets
  namespace: teaching-action
type: Opaque
stringData:
  # database access
  DATABASE_HOST: "localhost"
  DATABASE_PORT: "3306"
  DATABASE_DATABASE: "subject_approval_service"
  DATABASE_USERNAME: "guest"
  DATABASE_PASSWORD: "*********"
  DATABASE_DIALECT: "mysql"

  # rabbit credentials
  RABBIT_HOST: "amqp://localhost"
  RABBIT_PORT: "5672"
  RABBIT_USERNAME: "guest"
  RABBIT_PASSWORD: "*********"
  RABBIT_VHOST: "/"
  RABBIT_EXCHANGE: "sagittarius-a"
  RABBIT_TYPE_EXCHANGE: "fanout"
  RABBIT_QUEUE: "teaching-action.subject-approval-service"
  RABBIT_SIGNATURE: "academic-teaching.evaluation-system.subject_graded" #name event listener
  RABBIT_ROUTING_KEY: "sagittarius-a"
