version: '3.9'

services:
    mysql:
        image: mysql:8.0.32
        container_name: mysql_db
        restart: always
        ports:
            - '3306:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - mysql_local:/var/lib/mysql
            - ./c_dis-fisico/ej:/home/docs


volumes:
    mysql_local:
        external: true
