apiVersion: batch/v1
kind: CronJob
metadata:
  name: sign-ups-cronjob-consume-queue-local
  namespace: academic-administration-local
spec:
  schedule: "*/2 * * * *" #At every 2nd minute. https://crontab.guru/#*/2_*_*_*_*
  suspend: false
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: sign-ups-cronjob-local
            image: localhost:32000/sign-ups-app:latest
            envFrom:
            - secretRef:
                name: sign-ups-app-secret-local
            - configMapRef:
                name: sign-ups-app-config-local
            args:
            - /bin/sh
            - -c
            - php /app/artisan queue:consume --message-limit=200 --time-limit=20 --memory-limit=50
          restartPolicy: OnFailure
