apiVersion: v1
kind: Secret
metadata:
  name: sign-ups-app-secret-example
  namespace: academic-administration
type: Opaque
stringData:
    #CONFIG API ELASTICSEARCH
    ES_API_ID: "example"
    ES_API_KEY: "example"
    ES_CLOUD_ID: "example"
    #ELASTICSEARCH CONFIG
    ES_HOST: "127.0.0.1"
    ES_PORT: "9200"
    #CONFIG DATABASE SIRIUS
    DB_CONNECTION_SIRIUS: "mysql_example"
    DB_HOST: "127.0.0.1"
    DB_PORT: "3306"
    DB_DATABASE: "example"
    DB_USERNAME: "example"
    DB_PASSWORD: "example"
    #CONFIG DATABASE GUIAA
    DB_CONNECTION_GUIAA: "mysql_example"
    DB_HOST_GUIAA: "127.0.0.1"
    DB_PORT_GUIAA: "3306"
    DB_DATABASE_GUIAA: "example"
    DB_USERNAME_GUIAA: "example"
    DB_PASSWORD_GUIAA: "example"
    #CONFIG DATABASE UNIC
    DB_CONNECTION_UNIC: "mysql_example"
    DB_HOST_UNIC: "127.0.0.1"
    DB_PORT_UNIC: "3306"
    DB_DATABASE_UNIC: "example"
    DB_USERNAME_UNIC: "example" 
    DB_PASSWORD_UNIC: "example"
    #CONFIG DATABASE UNINCOL
    DB_CONNECTION_UNINCOL: "mysql_example"
    DB_HOST_UNINCOL: "127.0.0.1"
    DB_PORT_UNINCOL: "3306"
    DB_DATABASE_UNINCOL: "example"
    DB_USERNAME_UNINCOL: "example" 
    DB_PASSWORD_UNINCOL: "example"
    # NOMBRE DE LOS SG
    NAME_SIRIUS: "sirius"
    NAME_GUIAA: "guiaa"
    NAME_UNIC: "unic"
    NAME_UNINCOL: "unincol"
    #RABITTMQ QUEUE CONFIG
    RABBITMQ_HOST: "127.0.0.1"
    RABBITMQ_PORT: "5672"
    RABBITMQ_USER: "example"
    RABBITMQ_PASSWORD: "example"
    RABBITMQ_VHOST: "/"
    RABBITMQ_QUEUE: "academic-administration.sign-ups"
    RABBITMQ_EXCHANGE: "sagittarius-a"
    RABBITMQ_EXCHANGE_TYPE: "fanout"
    ENQUEUE_DSN: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}:${RABBITMQ_PORT}/${RABBITMQ_VHOST}"
    #ENQUEUE_DSN: "amqp://example:example@127.0.0.1:5672/%2f"