apiVersion: v1
kind: Secret
metadata:
  name: autoscore-api-service-secrets
  namespace: teaching-action
type: Opaque
stringData:
  #port
  PORT: "80"
  # database access
  DATABASE_HOST: "localhost"
  DATABASE_PORT: "3306"
  DATABASE_DATABASE: "autoscore_db"
  DATABASE_USERNAME: "guest"
  DATABASE_PASSWORD: "*********"
  DATABASE_DIALECT: "mysql"

  # rabbit credentials
  RABBIT_HOST: "amqp://localhost"
  RABBIT_PORT: "5672"
  RABBIT_USERNAME: "guest"
  RABBIT_PASSWORD: "*********"
  RABBIT_VHOST: "/"
  RABBIT_EXCHANGE: "sagittarius-a"
  RABBIT_TYPE_EXCHANGE: "fanout"
  RABBIT_QUEUE: "teaching-action.autoscore-service"
  RABBIT_SIGNATURE: "teaching-action.moodle.autoscore_activity_completed" #name event listener
  RABBIT_ROUTING_KEY: "sagittarius-a"
