apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscore-service-api-deployment
  namespace: teaching-action
  labels:
    app: autoscore-api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscore-api-service
      tier: backend
      stage: beta
      type: microservice
      track: stable
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: autoscore-api-service
        tier: backend
        stage: beta
        type: microservice
        track: stable
    spec:
      restartPolicy: Always
      containers:
        - name: autoscore-service-api
          image: API_IMAGE_NAME
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
          envFrom:
            - configMapRef:
                name: autoscore-service-config
            - secretRef:
                name: autoscore-api-service-secrets

