apiVersion: batch/v1
kind: CronJob
metadata:
  name: sign-ups-import-students-sirius
  namespace: academic-administration
spec:
  schedule: "0 0 * * *" #every day at 00:00
  suspend: false
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: sign-ups-cronjob
            image: PHP_IMAGE_NAME
            envFrom:
            - secretRef:
                name: sign-ups-app-secret
            - configMapRef:
                name: sign-ups-app-config
            args:
            - /bin/sh
            - -c
            - php artisan import:students -s sirius
          restartPolicy: OnFailure
