version: "3.8"
services:
  db-service:
    image: mysql:8.0.27
    container_name: db-container-autoscore
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: autoscore-db-schema
      MYSQL_USER: autoscore_user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE


  phpmyadmin-service:
    image: phpmyadmin/phpmyadmin:5.1.3
    container_name: phpmyadmin-container-autoscore
    restart: always
    environment:
      PMA_HOST: db-service
      PMA_USER: root
      PMA_PASSWORD: password
      PMA_ARBITRARY: 1
      PMA_PORT: 3306

    links:
      - 'db-service:db'
    ports:
      - "8885:80"
    


  backend_service:
    image: autoscore-image
    container_name: autoscore-service-container
    restart: always
    env_file:
      - .env.example
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "4001:4001"
    network_mode: host
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - db-service
      - phpmyadmin-service


