# version: "3.8"
# services:
#   db-service:
#     image: mysql:8.0.27
#     container_name: db-container
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_USER: autoscore_user
#       MYSQL_PASSWORD: password
#       MYSQL_DATABASE: autoscore-db-schema
#     ports:
#       - "33066:3306"
#     networks:
#       - autoscore-staging-deploy


#   backend_service:
#     image: autoscore-image
#     container_name: autoscore-service-container
#     restart: always
#     environment:
#       # database access
#       DB_USER: root
#       DB_PORT: 3306
#       DB_PASSWORD: password
#       DB_NAME: autoscore-db-schema
#       DB_HOST: db-service
#       # ### rabbit credentials
#       # RABBITMQ_HOST: amqp://35.222.192.45
#       # RABBITMQ_PORT: 5672
#       # RABBITMQ_USERNAME: guest
#       # RABBITMQ_PASSWORD: guest
#       # RABBITMQ_VHOST: /
#       # RABBITMQ_EXCHANGE: sagittarius-a
#       # RABBITMQ_EXCHANGE_TYPE: fanout
#       # RABBITMQ_QUEUE: teaching-action.autoscore-service
#       # RABBITMQ_NAME_EVENT: teaching-action.moodle.autoscore_activity_completed
#       # RABBIT_ROUTING_KEY: sagittarius-a
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#         - "3333:3333"
#     networks:
#       - autoscore-staging-deploy
#     volumes:
#       - .:/home/node/app
#       - /home/node/app/node_modules


#   rabbitmq:
#     image: rabbitmq:management-alpine
#     container_name: rabbitmq
#     restart: always
#     ports:
#       - 15672:15672
#       - 5672:5672
#     networks:
#       - autoscore-staging-deploy


#   phpmyadmin-service:
#     image: phpmyadmin/phpmyadmin:5.1.3
#     container_name: phpmyadmin-container
#     restart: always
#     # secrets:
#       # - db_root_password
#     environment:
#       PMA_HOST: db-service
#       PMA_USER: root
#       PMA_PASSWORD: password
#       PMA_ARBITRARY: 1
#       PMA_PORT: 3306

#     links:
#       - 'db-service:db'
#     ports:
#       - "8385:80"
#     networks:
#       - autoscore-staging-deploy
# networks:
#   autoscore-staging-deploy:








version: "3.8"
services:
  db-service:
    image: mysql:8.0.27
    container_name: db-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: autoscore-db-schema
      MYSQL_USER: autoscore_user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE


  phpmyadmin-service:
    image: phpmyadmin/phpmyadmin:5.1.3
    container_name: phpmyadmin-container
    restart: always
    environment:
      PMA_HOST: db-service
      PMA_USER: root
      PMA_PASSWORD: password
      PMA_ARBITRARY: 1
      PMA_PORT: 3306

    links:
      - 'db-service:db'
    ports:
      - "8885:80"


  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - 15672:15672
      - 5672:5672



  backend_service:
    image: autoscore-image
    container_name: autoscore-service-container
    restart: always
    env_file:
      - .env.example
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "4000:4000"
    network_mode: host
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - db-service
      - phpmyadmin-service
      - rabbitmq

