apiVersion: v1
kind: ConfigMap
metadata:
  name: subject-approval-config
  namespace: teaching-action
  labels:
    app: subject-approval-api-service
data:
  #port
  PORT: "80"
  #seed default environment configuration
  SEED_INSTITUTION_LOAD_FILE: 'institutions.production'
  #state approved sg
  STATE_APPROVED_SG: "approved"
